sonar.projectKey=frontend-crisisview
sonar.projectName=Frontend CrisisView
sonar.sources=app
sonar.exclusions=node_modules/**,.next/**,public/**
sonar.coverage.exclusions=**/* # Exclure les règles de couverture car on n'a pas de tests ici
sonar.sourceEncoding=UTF-8
